# Generated by Django 5.1.1 on 2024-10-21 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_student_address_remove_student_mobile_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='qualification',
            new_name='username',
        ),
    ]
