# Generated by Django 5.1.1 on 2024-10-28 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_studentfavoritecourse"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("detail", models.TextField(null=True)),
                ("add_time", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.student"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.teacher"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "9. Student Assignment",
            },
        ),
    ]
