# Generated by Django 5.1.1 on 2024-10-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_studentassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentassignment",
            name="student_status",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.DeleteModel(
            name="StudentFavoriteCourse",
        ),
    ]
