# Generated by Django 5.1.1 on 2024-11-03 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_studentassignment_student_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherStudentChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("msg_text", models.TextField()),
                ("msg_from", models.CharField(max_length=100)),
                ("msg_time", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.student"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.teacher"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "18. Teacher Student Messages",
            },
        ),
    ]
