# Generated by Django 5.1.1 on 2024-11-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_teacherstudentchat"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
