# Generated by Django 5.1.1 on 2024-12-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_alter_course_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="otp_digit",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="verify_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="teacher",
            name="otp_digit",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="verify_status",
            field=models.BooleanField(default=False),
        ),
    ]
